### ISSUE TITLE
AIRoot.js 类做大数据推送时出现websocket断连问题。

### ISSUE THREAD

**Issue by yeahpop** [uucckk/AIroot-JUS#3]
您好，很欣赏您的想法，虽然文档目前不够详细，但是整体真的很简单，我在看上此发的例子面，的AIRoot平台信息推送的代码，发现当推送数据大于5000的时候会出现websoket断连的问题。下面是我的代码。
# 我的代码
```html
<!-- 
	类注释
	@author sunxy
	@version 0.0
 -->
<@import value="component.*" />
<desktop>
	<style>
		body{
          	padding:10px;
			text-align:center;
          	
		}
      	.content{
        	background-color:#abcdef;  
      	}
      	.login{
        	color:#f0f0f0;
          	font-size:64px;
          	font-weight:bold;
      	}
      
	</style>
  	<vbox class="content" width="100%" height="100%">
      	<div width="100%" height="100%"></div>
		<div class="login">Index</div>
		<div class="login" style="font-size:24px;">C:\e\gowork.git\AIroot-JUS\Release\example\share</div>
 		<div width="100%" height="100%"></div>
  	</vbox>
  
	<script>
		import net.AIRoot;
		var ai:AIRoot = null;
		/**
		 * 默认初始化函数
		 */
		function init():void{
			ai = new AIRoot(location.hostname,80,"ws");
			ai.login("screen");
			ai.onOpen = function(){
				alert("connect");
				var str = "";
				for(var i = 0;i<5000;i++){
					str += "n";
				}
				return;
				setInterval(function(){
					ai.send("screen","",str);
				},100);
			};
			ai.onMessage = function(e){
				console.log(e);
			};
		}

		/**
		 * 析构函数
		 * 默认情况下可以不使用
		 */
		public function finalize():void{

		}
	</script>
</desktop>
```
# 抛出的错误
VM241:36 WebSocket is already in CLOSING or CLOSED state.
f3 @ VM241:36
setInterval (async)
f2 @ VM241:35
23:58:41.334 VM241:36 WebSocket is already in CLOSING or CLOSED state.
f3 @ VM241:36
setInterval (async)
f2 @ VM241:35
23:58:51.335 VM241:36 WebSocket is already in CLOSING or CLOSED state.
f3 @ VM241:36
setInterval (async)
f2 @ VM241:35
23:59:01.334 VM241:36 WebSocket is already in CLOSING or CLOSED state.
f3 @ VM241:36
setInterval (async)
f2 @ VM241:35
23:59:11.333 VM241:36 WebSocket is already in CLOSING or CLOSED state.
f3 @ VM241:36
setInterval (async)
f2 @ VM241:35
23:59:21.334 VM241:36 WebSocket is already in CLOSING or CLOSED state.
f3 @ VM241:36
setInterval (async)
f2 @ VM241:35
23:59:31.334 VM241:36 WebSocket is already in CLOSING or CLOSED state.
f3 @ VM241:36
setInterval (async)
f2 @ VM241:35
23:59:41.334 VM241:36 WebSocket is already in CLOSING or CLOSED state.
f3 @ VM241:36
setInterval (async)
f2 @ VM241:35
23:59:51.334 VM241:36 WebSocket is already in CLOSING or CLOSED state.
f3 @ VM241:36
setInterval (async)
f2 @ VM241:35
00:00:01.334 VM241:36 WebSocket is already in CLOSING or CLOSED state.
f3 @ VM241:36
setInterval (async)
f2 @ VM241:35
00:00:11.333

**Comment by uucckk** [comment]
感谢您的支持，这个问题我们在产品线上也出现了同样的错误，问题出现位置已经找到，本周会末更新。
次bug会在0.9.8版本修复。

**Comment by uucckk** [comment]
你好，我们已经更新了0.9.8，并且我们内部也正在测试，如果您方便的话可以测试下最新版本，我们等待您的反馈。

**Comment by yeahpop** [comment]
嗯嗯 现在好使了，我们测试已经没有出现问题。
支持，你的项目
