### ISSUE TITLE
Vue的模板在绑定数据方面很方便，JUS目前有类似的便捷功能吗？

### ISSUE THREAD

**Issue by yeahpop** [uucckk/AIroot-JUS#6]
比如说下面的例子：
```html
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>Vue</title>
<script src="https://cdn.staticfile.org/vue/2.4.2/vue.min.js"></script>
</head>
<body>
<div id="app">
  <p>{{ message }}</p>
</div>

<script>
new Vue({
  el: '#app',
  data: {
    message: 'Hello Vue.js!'
  }
})
</script>
</body>
</html>
```
如果一个页面有大量的数据需要添加，没有这样的功能实在是太麻烦了，希望看到JUS的解决方案。

**Comment by uucckk** [comment]
yeahpop 您好，当初开发JUS的时候主要考虑的是更好的兼容性、更好的面向对象式的全桟开发，JUS的开发目的不止着眼于DOM方面的操控，也是着眼于用表达语句和JavaScript的混合开发。
但是从目前来看，为了更好的为广大使用者服务，提高使用者的体验，我们开发团队决定引入模版绑定数据的方式来展现数据。
现在我们正在设计更为合理的模版版定方式，预计会在AIroot-JUS version1.0之前推出相应的API。
届时希望您能给我更多的支持和鼓励。

**Comment by uucckk** [comment]
您好，现在jus 0.9.10 版本已经加入了数据绑定功能和模板引擎功能，请先试用下，有问题，即使反馈
