### ISSUE TITLE
使用公共CSS标签描述的样式，在被继承之后失效

### ISSUE THREAD

**Issue by scatteredleaves** [uucckk/AIroot-JUS#7]
使用公共CSS标签描述的样式，在被继承之后失效
如下我新建一个SkyBack.html
```html
<!-- path:/code/SkyBack.html -->
<css>
  body{
    background-color:#aaaaff;
    width:1000px;
    height:700px;
  }
</css>
<div>
   <@content />
</div>
```
然后我新建一个模块，名字为SunSkyBack.html
```html
<!-- path:/code/SunSkyBack.html -->
<SkyBack>
  <!-- Sun 是我创建的一个太阳 -->
  <Sun />
</SkyBack>
```
但是，我们最终得到的效果为没有蓝色背景的效果，但是如果把css标签改为style标签是好使的。

**Comment by uucckk** [comment]
嗯 css 标签是我们新引入的属性，目的是为了减少style独立样式封装后的冗余，经过我们测试，确实存在您说的BUG，我们会在下一版本0.9.9解决。
感谢您的支持

**Comment by uucckk** [comment]
这个问题，我们已经在0.9.9 beta 中解决，最终发布会在0.9.9版本
